api_endpoint = "http://localhost:8181/api.php"
sparql_endpoint = "http://localhost:8989/bigdata/sparql"

[properties]
instance_of = "P1"
gtfs_id = "P2"
produced_by = "P3"
gtfs_short_name = "P4"
gtfs_long_name = "P5"
physical_mode = "P6"

[items]
line = 1
producer= 2
bus = 5
rail = 6
tram = 7
subway = 8
ferry = 9
cable_car = 10
gondola = 11
funicular = 12
