name: Rust

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check formating
      run: cargo fmt --all -- --check
